// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkuoD2xl8x8di0SdmEMxRtVwiD5mJ3vAo',
    appId: '1:560890787690:web:ecaa97df89a8b62f2d5713',
    messagingSenderId: '560890787690',
    projectId: 'fruit-salad-shop',
    authDomain: 'fruit-salad-shop.firebaseapp.com',
    storageBucket: 'fruit-salad-shop.firebasestorage.app',
    measurementId: 'G-KHQJDMF5G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5FeRpcumzXUfI2PnNVkGE2N3srJK9m70',
    appId: '1:560890787690:android:67afb60788ccf5642d5713',
    messagingSenderId: '560890787690',
    projectId: 'fruit-salad-shop',
    storageBucket: 'fruit-salad-shop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmH14Lzn6rD28UCkhEm73J5hIBAjWLZsY',
    appId: '1:560890787690:ios:aeb43b30c0baf8702d5713',
    messagingSenderId: '560890787690',
    projectId: 'fruit-salad-shop',
    storageBucket: 'fruit-salad-shop.firebasestorage.app',
    iosBundleId: 'com.example.fruiteSaladShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmH14Lzn6rD28UCkhEm73J5hIBAjWLZsY',
    appId: '1:560890787690:ios:aeb43b30c0baf8702d5713',
    messagingSenderId: '560890787690',
    projectId: 'fruit-salad-shop',
    storageBucket: 'fruit-salad-shop.firebasestorage.app',
    iosBundleId: 'com.example.fruiteSaladShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkuoD2xl8x8di0SdmEMxRtVwiD5mJ3vAo',
    appId: '1:560890787690:web:5c2202e0ba32e51e2d5713',
    messagingSenderId: '560890787690',
    projectId: 'fruit-salad-shop',
    authDomain: 'fruit-salad-shop.firebaseapp.com',
    storageBucket: 'fruit-salad-shop.firebasestorage.app',
    measurementId: 'G-GBJ0B8V6QM',
  );
}
